In [11]:
import numpy as np

In [12]:
# TODO: 1. Define the activation function
def tanh(x):
    return (np.exp(x) - np.exp(-x)) / (np.exp(x) + np.exp(-x))

def hard_tanh(x):
    return np.maximum(-1, np.minimum(1, x))

def softplus(x):
    return np.log(1 + np.exp(x))

def relu(x):
    return np.maximum(0, x)

def leaky_relu(x, alpha=0.1):
    return np.where(x > 0, x, alpha * x)

In [ ]:
def test_activation(activation_function):
    # TODO: 2. Change the Activation Function to Test
    activation_function = activation_function  # <-- Change this to test others 

    # Input Vector x (3 features + bias x0)
    x_raw = np.array([[0.5], [0.2], [0.1]])  # (3, 1)
    x = np.vstack(([1.0], x_raw))           # x0 = 1 added for bias -> (4, 1)

    # Define Fixed Weights (No randomness)
    W1 = np.array([
        [0.1,  0.1,  0.2,  0.3],
        [0.2, -0.3,  0.4,  0.1],
        [0.05, 0.2, -0.2, 0.1],
        [0.0,  0.3, -0.1, 0.2]
    ])  # Shape: (4 hidden, 4 input incl. bias)

    W2 = np.array([
        [0.2,  0.3, -0.1, 0.5,  0.1],
        [-0.2, 0.4,  0.3, -0.1, 0.2]
    ])  # Shape: (2 output, 5 hidden incl. z0 bias)
    
    # TODO: 4. Implement Forward Pass
    # Step 1: Compute pre-activation
    a1 = W1 @ x

    # Step 2: Apply activation function
    z1 = activation_function(a1)

    # Step 3: Add bias node z0 = 1 to hidden activations
    z1_aug = np.vstack(([1.0], z1))  # shape (5, 1)

    # Step 4: Compute output y
    y = W2 @ z1_aug

    # Print the results
    print("=== Activation Function:", activation_function.__name__, "===")
    print("Input x (with bias):\n", x.T)
    print("Hidden pre-activation a1:\n", a1.T)
    print("Hidden activation z1:\n", z1.T)
    print("Hidden layer with bias z1_aug:\n", z1_aug.T)
    print("Final output y:\n", y.T)

In [ ]:
test_activation(tanh)

=== Activation Function: tanh ===
Input x (with bias):
 [[1.  0.5 0.2 0.1]]
Hidden pre-activation a1:
 [[0.22 0.14 0.12 0.15]]
Hidden activation z1:
 [[0.21651806 0.13909245 0.1194273  0.14888503]]
Hidden layer with bias z1_aug:
 [[1.         0.21651806 0.13909245 0.1194273  0.14888503]]
Final output y:
 [[ 0.32564833 -0.05383076]]


In [15]:
test_activation(hard_tanh)

=== Activation Function: hard_tanh ===
Input x (with bias):
 [[1.  0.5 0.2 0.1]]
Hidden pre-activation a1:
 [[0.22 0.14 0.12 0.15]]
Hidden activation z1:
 [[0.22 0.14 0.12 0.15]]
Hidden layer with bias z1_aug:
 [[1.   0.22 0.14 0.12 0.15]]
Final output y:
 [[ 0.327 -0.052]]


In [16]:
test_activation(softplus)

=== Activation Function: softplus ===
Input x (with bias):
 [[1.  0.5 0.2 0.1]]
Hidden pre-activation a1:
 [[0.22 0.14 0.12 0.15]]
Hidden activation z1:
 [[0.80918502 0.76559518 0.7549461  0.77095705]]
Hidden layer with bias z1_aug:
 [[1.         0.80918502 0.76559518 0.7549461  0.77095705]]
Final output y:
 [[0.82076474 0.43204936]]


In [17]:
test_activation(relu)

=== Activation Function: relu ===
Input x (with bias):
 [[1.  0.5 0.2 0.1]]
Hidden pre-activation a1:
 [[0.22 0.14 0.12 0.15]]
Hidden activation z1:
 [[0.22 0.14 0.12 0.15]]
Hidden layer with bias z1_aug:
 [[1.   0.22 0.14 0.12 0.15]]
Final output y:
 [[ 0.327 -0.052]]


# Manually calculate the relu
input = [1.  0.5 0.2 0.1]

W1 = 
    [0.1,  0.1,  0.2,  0.3],
    [0.2, -0.3,  0.4,  0.1],
    [0.05, 0.2, -0.2, 0.1],
    [0.0,  0.3, -0.1, 0.2]

W2 =
    [0.2,  0.3, -0.1, 0.5,  0.1],
    [-0.2, 0.4,  0.3, -0.1, 0.2]

a1 = W1 @ input

a1 = [0.22 0.14 0.12 0.15] # (4,1)

z1 = relu(a1) = np.maximum(0, a1) # so there will be same

zi = [0.22 0.14 0.12 0.15] # (4,1)

add bias [1.0]

zi_aug = [1.   0.22 0.14 0.12 0.15] # (5,1)

output = W2 @ zi_aug

In [18]:
test_activation(leaky_relu)

=== Activation Function: leaky_relu ===
Input x (with bias):
 [[1.  0.5 0.2 0.1]]
Hidden pre-activation a1:
 [[0.22 0.14 0.12 0.15]]
Hidden activation z1:
 [[0.22 0.14 0.12 0.15]]
Hidden layer with bias z1_aug:
 [[1.   0.22 0.14 0.12 0.15]]
Final output y:
 [[ 0.327 -0.052]]
